# Generated by Django 3.2.8 on 2022-02-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Begining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prepared', models.DateField(auto_created=True)),
                ('person_preparing', models.CharField(blank=True, max_length=255)),
                ('expires_on', models.DateField(blank=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=255)),
                ('confirmed_on', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finished', models.DateField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('LotNo', models.CharField(blank=True, max_length=255, unique=True)),
                ('dillution_medium', models.CharField(blank=True, max_length=255)),
                ('final_qty', models.FloatField()),
                ('unit', models.CharField(max_length=5)),
                ('note', models.TextField(blank=True)),
                ('finish', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reagents.ending')),
                ('ingredient01', models.ManyToManyField(blank=True, related_name='_Reagents_reagent_ingredient01_+', to='Reagents.Reagent')),
                ('preparation', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reagents.begining')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maker', models.CharField(default='和光', max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('LotNo', models.CharField(max_length=255)),
                ('qty', models.FloatField()),
                ('unit', models.CharField(max_length=5)),
                ('used_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Reagents.reagent')),
            ],
        ),
    ]
