# Generated by Django 3.2.8 on 2022-02-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reagents', '0002_auto_20220222_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='ingredient01',
        ),
        migrations.AddField(
            model_name='reagent',
            name='ingredient',
            field=models.ManyToManyField(blank=True, related_name='_Reagents_reagent_ingredient_+', to='Reagents.Reagent'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
