# Generated by Django 3.2.8 on 2022-02-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reagents', '0003_auto_20220222_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='preparation',
        ),
        migrations.AddField(
            model_name='reagent',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reagent',
            name='confirmed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='date_prepared',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='image01',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reagent',
            name='person_preparing',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reagent',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Begining',
        ),
        migrations.DeleteModel(
            name='Ending',
        ),
    ]
