# Generated by Django 3.2.8 on 2022-02-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reagents', '0004_auto_20220222_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='image02',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reagent',
            name='image03',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
